/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuleTrackIdModuleIdRouteImport } from './routes/module.$trackId.$moduleId'

const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleTrackIdModuleIdRoute = ModuleTrackIdModuleIdRouteImport.update({
  id: '/module/$trackId/$moduleId',
  path: '/module/$trackId/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tracks': typeof TracksRoute
  '/module/$trackId/$moduleId': typeof ModuleTrackIdModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tracks': typeof TracksRoute
  '/module/$trackId/$moduleId': typeof ModuleTrackIdModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tracks': typeof TracksRoute
  '/module/$trackId/$moduleId': typeof ModuleTrackIdModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tracks' | '/module/$trackId/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tracks' | '/module/$trackId/$moduleId'
  id: '__root__' | '/' | '/tracks' | '/module/$trackId/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TracksRoute: typeof TracksRoute
  ModuleTrackIdModuleIdRoute: typeof ModuleTrackIdModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/$trackId/$moduleId': {
      id: '/module/$trackId/$moduleId'
      path: '/module/$trackId/$moduleId'
      fullPath: '/module/$trackId/$moduleId'
      preLoaderRoute: typeof ModuleTrackIdModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TracksRoute: TracksRoute,
  ModuleTrackIdModuleIdRoute: ModuleTrackIdModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
